### ISSUE TITLE
Feature request: sort favourites

### ISSUE THREAD

**Issue by Leimking** [bkury/skin.night#11]
I like the favourites-feature, but I cannot move or sort items. That would be very nice, thank you. :o)

**Comment by bkury** [comment]
I'm afraid there is no skin function to do that ... It wouldn't be impossible to code something like that but it would be very "hacky" and complex.

So for now you have to organize it yourself. Just delete an existing favorite and replace it with something else, it's not that big of a deal because you don't change favorites on a daily basis anyway, or do you? :-)
