### ISSUE TITLE
It is very difficult to use the Night skin to create or edit a Playlist

### ISSUE THREAD

**Issue by viking2** [bkury/skin.night#26]
I couldn't figure out how to use the Playlist Editor until I switched to the default (Estuary) skin.
Here is what is it looks like when I edit my Sci-Fi/Fantasy Playlist:

In Default skin:
![](https://i.gyazo.com/65a97d9331bea85e98f717cf1e408ffd.png)
in Night skin:
![](https://i.gyazo.com/9d978024ddb7cd59615d0bf7b767a64e.png)

**Comment by bkury** [comment]
Yes, I know. This dialog isn't used often so it wasn't a priority,

There are still a couple of dialogs which I haven't modified yet, so if you encounter a weird looking/broken dialog like that just ignore it for now. I will get to them as soon as I have finished the high priority stuff.

I'll close this for now because it's already on my GUI todo list but thanks for reporting!
