### ISSUE TITLE
dropped openpht support?

### ISSUE THREAD

**Issue by Spark-NV** [bkury/skin.night#30]
i love this skin on openpht. been using 1.8.6 for what seems like forever and just decided to check if there was an update for the skin and to my disbelief you did update it. but sadly it looks like its severely broken for openpht now.

is this intentional? was openpht support dropped all together?

**Comment by bkury** [comment]
Yes, I dropped support for it because OpenPHT isn't actively maintained for a long time now. The KODI version which OpenPHT is based on is also way too old to support the new skin features and ideas.

That's why I'm also working on a OpenPHT alternative/replacement called OpenHT. There is an older windows test version available here (Feel free to test it and let me know what you think) :
https://github.com/bkury/OpenHT/releases

I'm currently focusing on finishing my skin but a major OpenHT update should be ready within the next 2 months.

**Comment by Spark-NV** [comment]
Sad to hear about the openpht support being dropped, last time i used plexkodiconnect it was a bit too slow for my liking on everything. but i think ill give your openHT project a test drive and see if its any better.
gonna try incorporating it into a libreelec embedded image and test it out on my pi :)
